# version: "3.8"

services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    cap_add:
      - IPC_LOCK
    entrypoint: "/bin/sh"
    command: "/init-vault.sh"
    networks:
      - net_backend
      - net_database
    volumes:
          - ./services/vault/config:/vault/config
          - ./services/vault/data:/vault/data
          - ./services/vault/init-vault.sh:/init-vault.sh
    depends_on:
      postgres:
        condition: service_healthy

### SECURITY

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    environment:
      - PARANOIA=1
      - SEC_RULE_ENGINE=DetectionOnly
    ports:
      - "8000:80"
    volumes:
      - ./services/waf/default.conf:/etc/nginx/conf.d/waf.conf:ro
    networks:
      - net_gateway
    depends_on:
      frontend:
        condition: service_healthy
      gateway:
        condition: service_healthy
    restart: unless-stopped

### Database

  postgres:
    build:
      context: ./services/database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    networks:
      - net_backend
      - net_database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - net_database
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "php -r \"exit(@file_get_contents('http://127.0.0.1:8080')===false);\""]
      interval: 10s
      timeout: 3s
      retries: 20

### Backend

  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "5000"
      JWT_SECRET: "${JWT_SECRET}"
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    ports:
      - "5000:5000"
    networks:
      - net_backend
      - net_gateway
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"require('http').get('http://127.0.0.1:5000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""
        ]
      interval: 10s
      timeout: 3s
      retries: 20
  
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "5000"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    expose: 
      - "5000"
    networks:
      - net_backend
    depends_on:
      gateway:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"require('http').get('http://127.0.0.1:5000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""
        ]
      interval: 10s
      timeout: 3s
      retries: 20

  users-service:
    build:
      context: .
      dockerfile: ./services/users/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "5000"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    expose:
      - "5000"
    networks:
      - net_backend
    depends_on:
      - gateway
    restart: unless-stopped
    # volume: users_avatar_data:/app/users/uploads/avatar
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"require('http').get('http://127.0.0.1:5000/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""
        ]
      interval: 10s
      timeout: 3s
      retries: 20

### Frontend

  frontend:
    build:
      context: ./services/frontend
    expose:
      - "80" 
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - net_gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20

### Metrics

  project_health:
    build:
      context: ./services/project_health
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - net_backend
      - net_gateway
      - net_database
    depends_on:
      postgres:
        condition: service_healthy
      adminer:
        condition: service_healthy
      gateway:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      users-service:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/check.sh"]
      interval: 10s
      timeout: 3s
      retries: 3

### Dev

  frontend-dev:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend:/app
      - frontend_node_modules:/app/conf/node_modules
    command: >
      sh -lc "rm -rf /app/node_modules
      && ln -s /app/conf/node_modules /app/node_modules
      && cd /app
      && ./conf/node_modules/.bin/vite --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - net_gateway
    restart: unless-stopped
    profiles: ["dev"]

### Config

networks:
  net_database:
    name: net_database
  net_backend:
    name: net_backend
  net_gateway:
    name: net_gateway

volumes:
  postgresql_data:
  frontend_node_modules:
  # users_avatar_data:
