global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:5000"]

  - job_name: "frontend"
    static_configs:
      - targets: ["nginx_exporter:9113"]

