global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']


  - job_name: nginx
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [ "http_2xx" ]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "blackbox_exporter:9115"
    static_configs:
      - targets: ['http://gateway/']

